# environment.yml

name: nlp_flood_extract_env
channels:
  - conda-forge
  - anaconda
  - defaults
dependencies:
  - appdirs=1.4.4
  - asttokens=2.4.1
  - beautifulsoup4=4.12.2
  - blas=1.0
  - bottleneck=1.3.5
  - brotli=1.0.9
  - brotli-bin=1.0.9
  - brotli-python=1.0.9
  - bzip2=1.0.8
  - ca-certificates=2024.7.4
  - certifi=2024.7.4
  - cffi=1.16.0
  - charset-normalizer=2.0.4
  - click=8.1.7
  - colorama=0.4.6
  - comm=0.2.2
  - contourpy=1.0.5
  - cryptography=42.0.8
  - cycler=0.11.0
  - debugpy=1.8.2
  - decorator=5.1.1
  - docker-pycreds=0.4.0
  - exceptiongroup=1.2.2
  - executing=2.0.1
  - fonttools=4.25.0
  - freetype=2.12.1
  - giflib=5.2.1
  - gitdb=4.0.7
  - gitpython=3.1.37
  - icc_rt=2022.1.0
  - idna=3.4
  - importlib-metadata=8.0.0
  - importlib_metadata=8.0.0
  - intel-openmp=2023.1.0
  - ipykernel=6.29.5
  - ipython=8.26.0
  - jedi=0.19.1
  - joblib=1.2.0
  - jpeg=9e
  - jupyter_client=8.6.2
  - jupyter_core=5.7.2
  - kiwisolver=1.4.4
  - krb5=1.21.3
  - lerc=3.0
  - libbrotlicommon=1.0.9
  - libbrotlidec=1.0.9
  - libbrotlienc=1.0.9
  - libdeflate=1.17
  - libexpat=2.6.2
  - libffi=3.4.4
  - libpng=1.6.39
  - libprotobuf=3.20.3
  - libsodium=1.0.18
  - libsqlite=3.44.2
  - libtiff=4.5.1
  - libwebp=1.3.2
  - libwebp-base=1.3.2
  - libzlib=1.2.13
  - lz4-c=1.9.4
  - matplotlib-base=3.8.0
  - matplotlib-inline=0.1.7
  - mkl=2023.1.0
  - mkl-service=2.4.0
  - mkl_fft=1.3.8
  - mkl_random=1.2.4
  - munkres=1.1.4
  - nest-asyncio=1.6.0
  - numexpr=2.8.7
  - numpy=1.26.0
  - numpy-base=1.26.0
  - openjpeg=2.4.0
  - openssl=3.3.1
  - packaging=23.1
  - pandas=2.1.1
  - parso=0.8.4
  - pathtools=0.1.2
  - pickleshare=0.7.5
  - pillow=10.0.1
  - pip=23.3
  - platformdirs=4.2.2
  - plotly=5.9.0
  - prompt-toolkit=3.0.47
  - protobuf=3.20.3
  - psutil=5.9.0
  - pure_eval=0.2.2
  - pycparser=2.21
  - pygments=2.18.0
  - pyopenssl=24.0.0
  - pyparsing=3.0.9
  - pysocks=1.7.1
  - python=3.11.7
  - python-dateutil=2.8.2
  - python-tzdata=2023.3
  - python_abi=3.11
  - pytz=2023.3.post1
  - pywin32=306
  - pyyaml=6.0.1
  - pyzmq=26.0.3
  - regex=2023.10.3
  - requests=2.31.0
  - scikit-learn=1.2.2
  - scipy=1.11.3
  - sentry-sdk=1.9.0
  - setproctitle=1.2.2
  - setuptools=68.0.0
  - six=1.16.0
  - smmap=4.0.0
  - soupsieve=2.5
  - sqlite=3.41.2
  - stack_data=0.6.2
  - tbb=2021.8.0
  - tenacity=8.2.2
  - threadpoolctl=2.2.0
  - tk=8.6.13
  - tornado=6.4.1
  - tqdm=4.65.0
  - traitlets=5.14.3
  - typing_extensions=4.7.1
  - tzdata=2023c
  - ucrt=10.0.20348.0
  - vc=14.2
  - vc14_runtime=14.38.33130
  - vs2015_runtime=14.38.33130
  - wandb=0.15.12
  - wcwidth=0.2.13
  - wheel=0.41.2
  - win_inet_pton=1.1.0
  - xz=5.4.2
  - yaml=0.2.5
  - zeromq=4.3.5
  - zipp=3.19.2
  - zlib=1.2.13
  - zstd=1.5.5
  - pip:
      - aiohttp==3.9.1
      - aiosignal==1.3.1
      - annotated-types==0.6.0
      - anyio==3.7.1
      - attrs==23.1.0
      - boto3==1.34.144
      - botocore==1.34.144
      - cohere==5.5.8
      - cssselect==1.2.0
      - distro==1.8.0
      - fastavro==1.9.5
      - feedfinder2==0.0.4
      - feedparser==6.0.10
      - filelock==3.13.1
      - frozenlist==1.4.0
      - fsspec==2024.6.1
      - h11==0.14.0
      - httpcore==1.0.2
      - httpx==0.25.2
      - httpx-sse==0.4.0
      - huggingface-hub==0.23.4
      - jieba3k==0.35.1
      - jmespath==1.0.1
      - lxml==4.9.3
      - multidict==6.0.4
      - newspaper3k==0.2.8
      - nltk==3.8.1
      - openai==0.28.0
      - parameterized==0.9.0
      - pydantic==2.5.2
      - pydantic-core==2.14.5
      - python-dotenv==1.0.0
      - requests-file==1.5.1
      - s3transfer==0.10.2
      - sgmllib3k==1.0.0
      - sniffio==1.3.0
      - tinysegmenter==0.3
      - tldextract==5.0.1
      - tokenizers==0.19.1
      - types-requests==2.32.0.20240712
      - urllib3==2.2.2
      - yarl==1.9.4
